// --- ИСТОРИЯ ОБНОВЛЕНИЙ ---
const appChangelog = [
    { 
        date: "15 Мая 2026", 
        ru: "увеличили базу сатов", 
        en: "increased the sat database" 
    },
    { 
        date: "10 Мая 2026", 
        ru: "Оптимизация базы данных, удаление дубликатов сервисов.", 
        en: "Database optimization, removed duplicate services." 
    }
];

// --- БАЗА ИНСТРУМЕНТОВ ---
const sitesData = [
    // --- НЕЙРОСЕТИ (AI) ---
    {
        id: "google-ai-studio",
        name: "Google AI Studio",
        url: "https://aistudio.google.com/",
        price: "free",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "Бесплатный доступ к топовым моделям Gemini.", en: "Free access to top Gemini models." },
        fullDesc: { ru: "Официальная песочница от Google, где можно тестировать запросы к нейросети Gemini абсолютно бесплатно, а также получать API-ключи.", en: "Google's official sandbox to test Gemini API models for free." },
        pros: { ru: ["Полностью бесплатно", "Работает с фото и видео"], en: ["Completely free", "Multimodal"] },
        cons: { ru: ["В РФ нужен VPN"], en: ["VPN needed in some regions"] },
        keywords: ["ai", "google", "gemini", "api"],
        isHot: false,
        isNew: false
    },

    // --- НОВЫЕ ПОПОЛНЕНИЯ (МАЙ 2026) ---
    {
        id: "gamma-app",
        name: "Gamma App",
        url: "https://gamma.app/",
        price: "freemium",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "Создание презентаций и веб-страниц с помощью ИИ.", en: "Create presentations and webpages with AI." },
        fullDesc: { ru: "Генерирует готовые презентации, документы или веб-страницы по текстовому запросу за пару секунд. Форматирует текст и подбирает картинки самостоятельно.", en: "Generates beautiful presentations, docs, and webpages from a text prompt in seconds." },
        pros: { ru: ["Шикарный современный дизайн", "Экспорт в PDF/PPTX"], en: ["Beautiful modern design", "Export to PDF/PPTX"] },
        cons: { ru: ["Быстро заканчиваются бесплатные кредиты"], en: ["Free credits burn out quickly"] },
        keywords: ["gamma", "презентации", "дизайн", "ai", "слайды"],
        isHot: false,
        isNew: false
    },
    {
        id: "dotabuff",
        name: "Dotabuff",
        url: "https://www.dotabuff.com/",
        price: "freemium",
        category: { ru: "Игры", en: "Gaming" },
        desc: { ru: "Главный сервис статистики для Dota 2.", en: "The premier Dota 2 statistics platform." },
        fullDesc: { ru: "Отслеживает и анализирует каждый твой матч в Доте. Показывает винрейты героев, сборки предметов, подробные графики золота/опыта и тренды метагейма.", en: "Tracks and analyzes your Dota 2 matches. Provides hero win rates, item builds, and meta trends." },
        pros: { ru: ["Колоссальный объем статистики", "Удобные гайды по героям"], en: ["Massive amounts of stats", "Great hero guides"] },
        cons: { ru: ["Глубокая аналитика доступна только в Plus-подписке"], en: ["Advanced analysis requires Plus subscription"] },
        keywords: ["dota", "dota2", "дота", "статистика", "киберспорт"],
        isHot: false,
        isNew: false
    },
    {
        id: "dota2protracker",
        name: "Dota2ProTracker",
        url: "https://dota2protracker.com/",
        price: "free",
        category: { ru: "Игры", en: "Gaming" },
        desc: { ru: "Сборки и тренды от профессиональных игроков в Dota 2.", en: "Track matches and builds of pro Dota 2 players." },
        fullDesc: { ru: "Идеальный инструмент, чтобы смотреть, как прямо сейчас играют про-игроки (8к+ MMR). Показывает актуальные сборки предметов, раскачку скиллов и тайминги.", en: "See what pro players are building in high-MMR pubs. Tracks skill builds and item timings." },
        pros: { ru: ["Обновляется каждые несколько минут", "Только актуальная мета"], en: ["Updates every few minutes", "Pure high-level meta"] },
        cons: { ru: ["Интерфейс может показаться сложным для новичков"], en: ["Interface can be confusing for beginners"] },
        keywords: ["dota", "dota2", "дота", "протрекер", "киберспорт", "мета"],
        isHot: false,
        isNew: false
    },
    {
        id: "x-grok",
        name: "Grok AI",
        url: "https://x.com/i/grok",
        price: "freemium",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "Нейросеть от Илона Маска с доступом к инсайдам X.", en: "AI assistant by Elon Musk with real-time X data." },
        fullDesc: { ru: "Умный ассистент, интегрированный в соцсеть X (Twitter). Имеет доступ к самым свежим новостям и трендам интернета в режиме реального времени. Олицетворяет дерзкий стиль общения.", en: "AI assistant integrated into X. Has real-time access to global news, trends, and posts with a witty tone." },
        pros: { ru: ["Знает о событиях, случившихся минуту назад", "Генерация картинок без цензуры"], en: ["Knows events from minutes ago", "Uncensored image gen"] },
        cons: { ru: ["Доступен только внутри подписки X Premium"], en: ["Requires X Premium subscription"] },
        keywords: ["grok", "грок", "маск", "ai", "нейросеть", "twitter"],
        isHot: false,
        isNew: false
    },
    {
        id: "webflow",
        name: "Webflow",
        url: "https://webflow.com/",
        price: "freemium",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Профессиональный визуальный конструктор сайтов.", en: "Professional visual website builder and CMS." },
        fullDesc: { ru: "Мощная low-code платформа для дизайнеров и разработчиков. Позволяет верстать сайты визуально, генерируя на выходе чистейший и адаптивный HTML/CSS/JS код.", en: "Powerful low-code tool that gives you total control over HTML, CSS, and JS visually." },
        pros: { ru: ["Полная свобода дизайна", "Идеальный чистый код на выходе"], en: ["Total layout freedom", "Outputs production-ready code"] },
        cons: { ru: ["Очень сложный интерфейс, требует обучения"], en: ["Steep learning curve"] },
        keywords: ["webflow", "flow", "верстка", "nocode", "lowcode", "конструктор"],
        isHot: false,
        isNew: false
    },
    {
        id: "v0-dev",
        name: "v0 by Vercel",
        url: "https://v0.dev/",
        price: "freemium",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Генератор интерфейсов на основе текста.", en: "Generates UI components using text prompts." },
        fullDesc: { ru: "Нейросеть от создателей Vercel, которая по твоему текстовому описанию создаёт готовый адаптивный фронтенд-код интерфейса (React, Tailwind CSS, Shadcn UI).", en: "AI tool by Vercel that generates production-ready UI components using React and Tailwind." },
        pros: { ru: ["Невероятная скорость прототипирования", "Код можно сразу копировать в проект"], en: ["Insane prototyping speed", "Copy-paste ready code"] },
        cons: { ru: ["Иногда путает сложные JS-логики"], en: ["Can struggle with complex JS logic"] },
        keywords: ["v0", "vercel", "фронтенд", "react", "tailwind", "ai"],
        isHot: false,
        isNew: false
    },

    {
        id: "chatgpt",
        name: "ChatGPT",
        url: "https://chatgpt.com/",
        price: "freemium",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "Самая популярная нейросеть в мире.", en: "The most popular AI in the world." },
        fullDesc: { ru: "Универсальный помощник от OpenAI. Пишет код, сочиняет тексты, анализирует данные и помогает в обучении.", en: "Universal assistant by OpenAI. Writes code, texts, analyzes data." },
        pros: { ru: ["Лучшее понимание контекста", "Огромная база знаний"], en: ["Best context understanding", "Huge knowledge base"] },
        cons: { ru: ["Лучшая модель (GPT-4) платная"], en: ["Best model is paid"] },
        keywords: ["chatgpt", "openai", "текст", "код", "ai"],
        isHot: false,
        isNew: false
    },
    {
        id: "leonardo-ai",
        name: "Leonardo.ai",
        url: "https://leonardo.ai/",
        price: "freemium",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "Генерация крутых артов и текстур.", en: "High-quality art generation." },
        fullDesc: { ru: "Мощная платформа для создания изображений. Идеально подходит для концепт-артов, текстур и дизайна персонажей.", en: "Powerful platform for creating images. Great for concept art and textures." },
        pros: { ru: ["Ежедневные бесплатные токены", "Много настроек"], en: ["Daily free tokens", "Advanced settings"] },
        cons: { ru: ["Сложный интерфейс для новичков"], en: ["Steep learning curve"] },
        keywords: ["art", "картинки", "дизайн", "генерация"],
        isHot: false,
        isNew: false
    },
    {
        id: "midjourney",
        name: "Midjourney",
        url: "https://midjourney.com/",
        price: "paid",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "Фотореалистичные изображения по тексту.", en: "Photorealistic images from text." },
        fullDesc: { ru: "Безоговорочный лидер в генерации картинок. Создает невероятно красивые и детализированные изображения любого стиля.", en: "Absolute leader in image generation. Creates incredibly beautiful images." },
        pros: { ru: ["Непревзойденное качество", "Понимание сложных стилей"], en: ["Unmatched quality", "Understands complex styles"] },
        cons: { ru: ["Нет бесплатной версии", "Работает через Discord"], en: ["No free version", "Works via Discord"] },
        keywords: ["mj", "фото", "арт", "нейросеть"],
        isHot: false,
        isNew: false
    },
    {
        id: "suno-ai",
        name: "Suno AI",
        url: "https://suno.com/",
        price: "freemium",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "Создание полноценных песен с вокалом.", en: "Create full songs with vocals." },
        fullDesc: { ru: "Нейросеть, которая за секунды генерирует песни в любом жанре (рок, поп, рэп) с отличным вокалом и музыкой по вашему тексту.", en: "AI that generates songs in any genre with great vocals based on your text." },
        pros: { ru: ["Отличное качество музыки", "50 бесплатных кредитов в день"], en: ["Great music quality", "50 free daily credits"] },
        cons: { ru: ["Иногда вокал звучит как робот"], en: ["Vocals can sometimes sound robotic"] },
        keywords: ["музыка", "песни", "звук", "вокал"],
        isHot: false,
        isNew: false
    },
    {
        id: "perplexity",
        name: "Perplexity",
        url: "https://www.perplexity.ai/",
        price: "freemium",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "ИИ-поисковик с реальными ссылками.", en: "AI search engine with citations." },
        fullDesc: { ru: "Замена Google. Ищет информацию в интернете и выдает готовый ответ со ссылками на источники. Не придумывает факты.", en: "Google alternative. Searches the web and gives compiled answers with sources." },
        pros: { ru: ["Не галлюцинирует", "Удобно для ресерча"], en: ["No hallucinations", "Great for research"] },
        cons: { ru: ["Иногда не находит глубокую информацию"], en: ["Sometimes misses deep info"] },
        keywords: ["поиск", "google", "ресерч", "факты"],
        isHot: false,
        isNew: false
    },

    // --- ДИЗАЙН (DESIGN) ---
    {
        id: "figma",
        name: "Figma",
        url: "https://www.figma.com/",
        price: "freemium",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "Стандарт индустрии для веб-дизайна.", en: "Industry standard for web design." },
        fullDesc: { ru: "Главный инструмент дизайнеров. Позволяет создавать интерфейсы сайтов, приложений и прототипы прямо в браузере.", en: "Main tool for designers to create interfaces and prototypes in the browser." },
        pros: { ru: ["Бесплатно для старта", "Совместная работа"], en: ["Free to start", "Collaboration features"] },
        cons: { ru: ["Требует времени на изучение"], en: ["Takes time to learn"] },
        keywords: ["дизайн", "ui", "ux", "интерфейс"],
        isHot: false,
        isNew: false
    },
    {
        id: "photopea",
        name: "Photopea",
        url: "https://www.photopea.com/",
        price: "free",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "Бесплатный клон Photoshop в браузере.", en: "Free browser-based Photoshop clone." },
        fullDesc: { ru: "Полноценный графический редактор, который открывает файлы PSD, AI, XD. Имеет почти все функции классического Фотошопа.", en: "Full graphic editor that opens PSD, AI files. Has almost all PS features." },
        pros: { ru: ["Поддержка PSD", "Не нужно устанавливать"], en: ["PSD support", "No installation needed"] },
        cons: { ru: ["Есть рекламный баннер сбоку"], en: ["Has ad banner on the side"] },
        keywords: ["фотошоп", "редактор", "psd", "фото"],
        isHot: false,
        isNew: false
    },
    {
        id: "cleanup-pictures",
        name: "Cleanup.pictures",
        url: "https://cleanup.pictures/",
        price: "freemium",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "Удаление объектов с фото за секунды.", en: "Remove objects from photos in seconds." },
        fullDesc: { ru: "Умный ластик на базе ИИ. Закрасьте лишний объект, человека или текст, и нейросеть аккуратно его удалит.", en: "AI-powered eraser. Paint over an object and AI removes it seamlessly." },
        pros: { ru: ["Очень быстро", "Не требует регистрации"], en: ["Very fast", "No registration"] },
        cons: { ru: ["HD-качество только в платной версии"], en: ["HD quality is paid"] },
        keywords: ["фото", "ластик", "ретушь", "удалить"],
        isHot: false,
        isNew: false
    },
    {
        id: "coolors",
        name: "Coolors",
        url: "https://coolors.co/",
        price: "freemium",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "Генератор идеальных цветовых палитр.", en: "Perfect color palette generator." },
        fullDesc: { ru: "Супербыстрый инструмент для создания цветовых схем. Нажимаете пробел — получаете новые цвета, которые идеально сочетаются. Отлично для веба и интерьеров.", en: "Superfast tool to generate matching color palettes by pressing space." },
        pros: { ru: ["Экспорт в CSS/PDF", "Огромная библиотека"], en: ["Export to CSS/PDF", "Huge library"] },
        cons: { ru: ["Реклама в бесплатной версии"], en: ["Ads in free version"] },
        keywords: ["цвет", "палитра", "css", "стиль", "интерьер"],
        isHot: false,
        isNew: false
    },
    {
        id: "remove-bg",
        name: "Remove.bg",
        url: "https://remove.bg",
        price: "freemium",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "Идеальное удаление фона с фото.", en: "Perfect background removal." },
        fullDesc: { ru: "Сервис использует ИИ для вырезания главного объекта. Идеально для подготовки портретов и коллажей.", en: "Uses AI to cut out the main object. Great for portraits and collages." },
        pros: { ru: ["Работает без кликов", "Идеально вырезает волосы"], en: ["Zero clicks", "Cuts hair perfectly"] },
        cons: { ru: ["Бесплатное скачивание в низком разрешении"], en: ["Free download is low res"] },
        keywords: ["фон", "вырезать", "png", "фото"],
        isHot: false,
        isNew: false
    },
    {
        id: "unsplash",
        name: "Unsplash",
        url: "https://unsplash.com/",
        price: "free",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "Бесплатные стоковые фото высокого качества.", en: "Free high-quality stock photos." },
        fullDesc: { ru: "Огромная библиотека профессиональных фотографий, которые можно использовать бесплатно даже в коммерческих целях.", en: "Huge library of professional photos free for commercial use." },
        pros: { ru: ["Невероятное качество", "Без лицензионных ограничений"], en: ["Incredible quality", "No license restrictions"] },
        cons: { ru: ["Много заезженных картинок"], en: ["Some photos are overused"] },
        keywords: ["фото", "сток", "картинки", "фон"],
        isHot: false,
        isNew: false
    },
    {
        id: "fontjoy",
        name: "Fontjoy",
        url: "https://fontjoy.com/",
        price: "free",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "ИИ-генератор сочетаний шрифтов.", en: "AI font pairing generator." },
        fullDesc: { ru: "Помогает подобрать шрифты (заголовок, подзаголовок, текст), которые идеально смотрятся вместе на сайте.", en: "Helps pair fonts (header, subheader, body) that look great together." },
        pros: { ru: ["Очень просто использовать", "Интеграция с Google Fonts"], en: ["Very easy to use", "Google Fonts integration"] },
        cons: { ru: ["Иногда выдает странные результаты"], en: ["Sometimes gives weird results"] },
        keywords: ["шрифты", "типографика", "текст"],
        isHot: false,
        isNew: false
    },

    // --- ИНСТРУМЕНТЫ (TOOLS) ---
    {
        id: "ilovepdf",
        name: "iLovePDF",
        url: "https://www.ilovepdf.com/",
        price: "freemium",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Всё, что можно сделать с PDF файлами.", en: "Everything you can do with PDF files." },
        fullDesc: { ru: "Универсальный комбайн: объединить, разделить, сжать, конвертировать в Word/Excel/JPG и разблокировать PDF.", en: "Universal tool: merge, split, compress, convert to Word/Excel/JPG." },
        pros: { ru: ["Много функций", "Простой интерфейс"], en: ["Many features", "Simple UI"] },
        cons: { ru: ["Ограничения на размер в бесплатной версии"], en: ["Size limits in free version"] },
        keywords: ["pdf", "сжать", "конвертер", "ворд"],
        isHot: false,
        isNew: false
    },
    {
        id: "wetransfer",
        name: "WeTransfer",
        url: "https://wetransfer.com/",
        price: "freemium",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Отправка тяжелых файлов (до 2 ГБ).", en: "Send heavy files (up to 2GB)." },
        fullDesc: { ru: "Самый быстрый способ передать тяжелый файл клиенту или другу. Загружаете файл — получаете короткую ссылку.", en: "Fastest way to send large files. Upload and get a short link." },
        pros: { ru: ["Без регистрации", "Красивый интерфейс"], en: ["No registration", "Beautiful UI"] },
        cons: { ru: ["Файлы удаляются через 7 дней"], en: ["Files expire in 7 days"] },
        keywords: ["файлы", "обменник", "ссылка", "передача"],
        isHot: false,
        isNew: false
    },
    {
        id: "tinypng",
        name: "TinyPNG",
        url: "https://tinypng.com/",
        price: "freemium",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Сжатие картинок без потери качества.", en: "Image compression without quality loss." },
        fullDesc: { ru: "Уменьшает вес PNG, JPG и WebP файлов на 50-80%, визуально сохраняя идеальное качество. Мастхэв для сайтов.", en: "Reduces image weight by 50-80% keeping perfect visual quality." },
        pros: { ru: ["Милая панда", "Лучший алгоритм сжатия"], en: ["Cute panda", "Best compression algorithm"] },
        cons: { ru: ["Максимум 20 файлов за раз"], en: ["Max 20 files at once"] },
        keywords: ["сжатие", "png", "jpg", "оптимизация"],
        isHot: false,
        isNew: false
    },
    {
        id: "cloudconvert",
        name: "CloudConvert",
        url: "https://cloudconvert.com/",
        price: "freemium",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Конвертер «всё во всё».", en: "Convert everything to everything." },
        fullDesc: { ru: "Поддерживает более 200 форматов (аудио, видео, документы, архивы). Отлично справляется с редкими форматами.", en: "Supports 200+ formats. Great for rare file types." },
        pros: { ru: ["Поддерживает вообще всё", "Высокое качество"], en: ["Supports everything", "High quality"] },
        cons: { ru: ["Лимит 25 конвертаций в день бесплатно"], en: ["Limit 25 conversions/day free"] },
        keywords: ["конвертер", "формат", "видео", "аудио"],
        isHot: false,
        isNew: false
    },
    {
        id: "notion",
        name: "Notion",
        url: "https://www.notion.so/",
        price: "freemium",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Универсальное рабочее пространство.", en: "All-in-one workspace." },
        fullDesc: { ru: "Заметки, базы данных, канбан-доски, календари — всё в одном месте. Идеально для планирования жизни и проектов.", en: "Notes, databases, boards, calendars. Perfect for planning." },
        pros: { ru: ["Невероятная гибкость", "Красивый дизайн"], en: ["Incredible flexibility", "Beautiful design"] },
        cons: { ru: ["Медленно работает без интернета"], en: ["Slow without internet"] },
        keywords: ["заметки", "планирование", "база", "таск-трекер"],
        isHot: false,
        isNew: false
    },

    // --- РАЗРАБОТКА (DEV) ---
    {
        id: "roadmap-sh",
        name: "Roadmap.sh",
        url: "https://roadmap.sh/",
        price: "free",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Пошаговые планы развития разработчиков.", en: "Step-by-step developer roadmaps." },
        fullDesc: { ru: "Визуальные дорожные карты, показывающие, какие технологии учить шаг за шагом (Frontend, Backend, Flutter и т.д.).", en: "Visual roadmaps showing what tech to learn step by step." },
        pros: { ru: ["Идеально для новичков", "Постоянно обновляется"], en: ["Perfect for beginners", "Always updated"] },
        cons: { ru: ["Нет курсов, только план"], en: ["Only roadmaps, no courses"] },
        keywords: ["учеба", "путь", "программирование", "карта"],
        isHot: false,
        isNew: false
    },
    {
        id: "can-i-use",
        name: "Can I Use",
        url: "https://caniuse.com/",
        price: "free",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Проверка поддержки CSS/JS в браузерах.", en: "Check CSS/JS support in browsers." },
        fullDesc: { ru: "Справочник, который показывает, будет ли конкретная фишка (например, CSS Grid) работать в старых версиях Safari или Chrome.", en: "Shows if a specific web feature works in various browser versions." },
        pros: { ru: ["Сверхточная статистика", "Незаменимо для верстки"], en: ["Accurate stats", "Essential for coding"] },
        cons: { ru: ["Специфичный интерфейс"], en: ["Specific UI"] },
        keywords: ["css", "html", "браузер", "верстка"],
        isHot: false,
        isNew: false
    },
    {
        id: "jsonlint",
        name: "JSONLint",
        url: "https://jsonlint.com/",
        price: "free",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Валидатор и форматтер JSON.", en: "JSON validator and formatter." },
        fullDesc: { ru: "Самый простой способ проверить свой JSON-код на ошибки (лишние запятые, скобки) и красиво его отформатировать.", en: "Easiest way to check JSON for errors and format it beautifully." },
        pros: { ru: ["Мгновенный результат", "Показывает строку с ошибкой"], en: ["Instant results", "Points out error line"] },
        cons: { ru: ["Много рекламы на сайте"], en: ["Ads on site"] },
        keywords: ["json", "код", "ошибка", "формат"],
        isHot: false,
        isNew: false
    },
    {
        id: "devdocs",
        name: "DevDocs",
        url: "https://devdocs.io/",
        price: "free",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Вся документация в одном месте.", en: "All documentation in one place." },
        fullDesc: { ru: "Объединяет официальные документации по HTML, CSS, JS, React, Python и сотням других языков. Работает оффлайн!", en: "Combines official docs for HTML, CSS, JS, Python, etc. Works offline!" },
        pros: { ru: ["Работает без интернета", "Мгновенный поиск"], en: ["Works offline", "Instant search"] },
        cons: { ru: ["Не для новичков (это не туториалы)"], en: ["Not a tutorial site"] },
        keywords: ["доки", "справочник", "код", "язык"],
        isHot: false,
        isNew: false
    },
    {
        id: "flutterflow",
        name: "FlutterFlow",
        url: "https://flutterflow.io/",
        price: "freemium",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Создание приложений без кода на Flutter.", en: "No-code app builder on Flutter." },
        fullDesc: { ru: "Позволяет собирать кроссплатформенные мобильные и веб-приложения визуально (drag-and-drop), а затем экспортировать чистый код на Dart/Flutter.", en: "Build cross-platform mobile & web apps visually and export clean Flutter code." },
        pros: { ru: ["Экспорт реального кода", "Мощные анимации"], en: ["Export real code", "Powerful animations"] },
        cons: { ru: ["Экспорт кода только в платной версии"], en: ["Code export is paid"] },
        keywords: ["flutter", "dart", "мобилка", "nocode"],
        isHot: false,
        isNew: false
    },
    {
        id: "codesandbox",
        name: "CodeSandbox",
        url: "https://codesandbox.io/",
        price: "freemium",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Онлайн-среда разработки.", en: "Online web development environment." },
        fullDesc: { ru: "Полноценный редактор кода в браузере. Идеально для быстрого прототипирования сайтов на React, Vue или обычного HTML/JS.", en: "Full code editor in the browser. Great for prototyping React, Vue, or HTML/JS." },
        pros: { ru: ["Мгновенный запуск", "Удобно делиться кодом"], en: ["Instant start", "Easy to share code"] },
        cons: { ru: ["Приватные песочницы платные"], en: ["Private sandboxes are paid"] },
        keywords: ["код", "редактор", "веб", "js"],
        isHot: false,
        isNew: false
    },
    {
        id: "github-pages",
        name: "GitHub Pages",
        url: "https://pages.github.com/",
        price: "free",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Бесплатный хостинг для сайтов.", en: "Free hosting for websites." },
        fullDesc: { ru: "Официальный инструмент GitHub для превращения репозиториев в автономные, быстрые и бесплатные веб-сайты.", en: "GitHub's official tool to turn repositories into fast, free websites." },
        pros: { ru: ["Вечный бесплатный хостинг", "Свой домен бесплатно"], en: ["Forever free hosting", "Custom domains"] },
        cons: { ru: ["Только статические сайты (без бэкенда)"], en: ["Static sites only (no backend)"] },
        keywords: ["хостинг", "github", "сайт", "деплой"],
        isHot: false,
        isNew: false
    },

    // --- ПРИВАТНОСТЬ (PRIVACY) ---
    {
        id: "superlogout",
        name: "SuperLogout",
        url: "https://superlogout.com/",
        price: "free",
        category: { ru: "Приватность", en: "Privacy" },
        desc: { ru: "Мгновенный выход из всех аккаунтов.", en: "Instant logout from all accounts." },
        fullDesc: { ru: "Сайт-скрипт. Заходите, и он автоматически разлогинивает вас в Google, Amazon, Steam и еще 30 сервисах. Осторожно!", en: "Instantly logs you out of 30+ major web services just by visiting." },
        pros: { ru: ["Отлично для публичных ПК", "Очень быстро"], en: ["Great for public PCs", "Very fast"] },
        cons: { ru: ["Выходит без предупреждения!"], en: ["Logs out without warning!"] },
        keywords: ["выход", "аккаунт", "безопасность", "logout"],
        isHot: false,
        isNew: false
    },
    {
        id: "tempmail",
        name: "TempMail",
        url: "https://temp-mail.org/",
        price: "freemium",
        category: { ru: "Приватность", en: "Privacy" },
        desc: { ru: "Одноразовая почта без регистрации.", en: "Disposable email without registration." },
        fullDesc: { ru: "Спасает от спама. Выдает случайный email, на который можно получить код подтверждения. Письма скоро удаляются.", en: "Saves from spam. Gives a random email to receive confirmation codes." },
        pros: { ru: ["Полная анонимность", "Защита от спама"], en: ["Full anonymity", "Spam protection"] },
        cons: { ru: ["Некоторые сайты блокируют эту почту"], en: ["Some sites block these emails"] },
        keywords: ["почта", "спам", "email", "анонимно"],
        isHot: false,
        isNew: false
    },
    {
        id: "have-i-been-pwned",
        name: "Have I Been Pwned",
        url: "https://haveibeenpwned.com/",
        price: "free",
        category: { ru: "Приватность", en: "Privacy" },
        desc: { ru: "Проверка утечек паролей и почты.", en: "Check if email/password is compromised." },
        fullDesc: { ru: "Введите свой email, и сайт покажет, в каких базах хакеров светилась ваша почта.", en: "Enter email to see if it was in any major data breaches." },
        pros: { ru: ["Огромная база утечек", "Безопасно использовать"], en: ["Huge breach database", "Safe to use"] },
        cons: { ru: ["Может вызвать панику :)"], en: ["Might cause panic :)"] },
        keywords: ["пароль", "утечка", "хакеры", "база"],
        isHot: false,
        isNew: false
    },
    {
        id: "virustotal",
        name: "VirusTotal",
        url: "https://www.virustotal.com/",
        price: "free",
        category: { ru: "Приватность", en: "Privacy" },
        desc: { ru: "Проверка ссылок и файлов на вирусы.", en: "Check links and files for viruses." },
        fullDesc: { ru: "Прогоняет любой файл или ссылку сразу через 70+ антивирусов (Касперский, Dr.Web, ESET) за пару секунд.", en: "Scans any file or link with 70+ antiviruses at once." },
        pros: { ru: ["Абсолютно надежно", "Сканирует ссылки до перехода"], en: ["Absolutely reliable", "Scans URLs before clicking"] },
        cons: { ru: ["Ограничение размера файла (650 МБ)"], en: ["File size limit 650MB"] },
        keywords: ["вирус", "троян", "файл", "сканер"],
        isHot: false,
        isNew: false
    },

    // --- ОБУЧЕНИЕ И НАУКА (EDUCATION) ---
    {
        id: "wolframalpha",
        name: "WolframAlpha",
        url: "https://www.wolframalpha.com/",
        price: "freemium",
        category: { ru: "Обучение", en: "Education" },
        desc: { ru: "Вычислительная поисковая система.", en: "Computational knowledge engine." },
        fullDesc: { ru: "Идеально для студентов. Решает сложные математические уравнения, строит графики, выдает факты по химии, географии и физике с пошаговыми решениями.", en: "Perfect for students. Solves complex math equations, provides facts on chemistry, geography, and physics." },
        pros: { ru: ["Решает почти всё", "Показывает графики"], en: ["Solves almost anything", "Shows graphs"] },
        cons: { ru: ["Пошаговое решение только в PRO"], en: ["Step-by-step is PRO only"] },
        keywords: ["математика", "химия", "калькулятор", "учеба"],
        isHot: false,
        isNew: false
    },
    {
        id: "desmos",
        name: "Desmos",
        url: "https://www.desmos.com/calculator",
        price: "free",
        category: { ru: "Обучение", en: "Education" },
        desc: { ru: "Продвинутый графический калькулятор.", en: "Advanced graphing calculator." },
        fullDesc: { ru: "Бесплатный, быстрый и невероятно красивый графический калькулятор прямо в браузере. Незаменим для геометрии и алгебры.", en: "Free, fast, and beautiful graphing calculator in your browser." },
        pros: { ru: ["Моментальная отрисовка", "Понятный интерфейс"], en: ["Instant rendering", "Clean UI"] },
        cons: { ru: ["Требует знания математического синтаксиса"], en: ["Requires math syntax knowledge"] },
        keywords: ["график", "математика", "геометрия", "калькулятор"],
        isHot: false,
        isNew: false
    },
    {
        id: "ptable",
        name: "Ptable",
        url: "https://ptable.com/",
        price: "free",
        category: { ru: "Обучение", en: "Education" },
        desc: { ru: "Интерактивная таблица Менделеева.", en: "Interactive periodic table." },
        fullDesc: { ru: "Самая подробная динамическая таблица химических элементов. Показывает свойства, орбитали, изотопы и соединения при разных температурах.", en: "The most detailed dynamic periodic table with properties, orbitals, and compounds." },
        pros: { ru: ["Очень наглядно", "Много языков"], en: ["Very visual", "Many languages"] },
        cons: { ru: ["Слегка перегруженный интерфейс"], en: ["Slightly cluttered UI"] },
        keywords: ["химия", "элементы", "наука", "таблица"],
        isHot: false,
        isNew: false
    },
    {
        id: "briefly",
        name: "Briefly",
        url: "https://briefly.ru/",
        price: "free",
        category: { ru: "Обучение", en: "Education" },
        desc: { ru: "Краткие содержания всех книг.", en: "Short summaries of books." },
        fullDesc: { ru: "Огромная библиотека кратких содержаний произведений мировой и русской литературы. Спасение перед экзаменами и уроками.", en: "Huge library of literature summaries. A lifesaver for exams." },
        pros: { ru: ["Читается за 10-15 минут", "Есть аудиоверсии"], en: ["Reads in 10-15 mins", "Audio versions available"] },
        cons: { ru: ["Не заменяет чтение оригинала :)"], en: ["Doesn't replace the original :)"] },
        keywords: ["литература", "книги", "кратко", "учеба"],
        isHot: false,
        isNew: false
    },

    // --- АРХИТЕКТУРА И 3D (ARCHITECTURE & 3D) ---
    {
        id: "textures-com",
        name: "Textures.com",
        url: "https://www.textures.com/",
        price: "freemium",
        category: { ru: "Архитектура", en: "Architecture" },
        desc: { ru: "Крупнейшая база 3D текстур.", en: "Largest database of 3D textures." },
        fullDesc: { ru: "Незаменимый сайт для архитекторов и 3D-художников. Кирпич, стекло, дерево, металл — тысячи бесшовных текстур и PBR-материалов для рендера.", en: "Essential for architects and 3D artists. Thousands of seamless textures and PBR materials." },
        pros: { ru: ["15 бесплатных кредитов каждый день", "Шикарное качество"], en: ["15 free daily credits", "Amazing quality"] },
        cons: { ru: ["8K текстуры только за деньги"], en: ["8K textures are paid"] },
        keywords: ["3d", "текстуры", "архитектура", "рендер"],
        isHot: false,
        isNew: false
    },
    {
        id: "planner-5d",
        name: "Planner 5D",
        url: "https://planner5d.com/",
        price: "freemium",
        category: { ru: "Архитектура", en: "Architecture" },
        desc: { ru: "Дизайн интерьера и архитектуры.", en: "Interior and architecture design." },
        fullDesc: { ru: "Удобный инструмент для планировки квартир, домов и участков. Позволяет делать 2D планы и сразу смотреть их в 3D (с мебелью, террасами и крышами).", en: "Tool for planning houses and lots. 2D plans instantly converted to 3D with furniture." },
        pros: { ru: ["Простота", "Хороший каталог объектов"], en: ["Simplicity", "Good object catalog"] },
        cons: { ru: ["HD-рендеры платные"], en: ["HD renders are paid"] },
        keywords: ["дом", "интерьер", "планировка", "архитектура"],
        isHot: false,
        isNew: false
    },
    {
        id: "sketchfab",
        name: "Sketchfab",
        url: "https://sketchfab.com/",
        price: "freemium",
        category: { ru: "Архитектура", en: "Architecture" },
        desc: { ru: "Просмотр и публикация 3D-моделей.", en: "View and publish 3D models." },
        fullDesc: { ru: "Крупнейшая платформа для публикации, обмена и покупки 3D-моделей. Можно крутить модели прямо в браузере.", en: "Platform for sharing and buying 3D models. Inspect models directly in browser." },
        pros: { ru: ["Много бесплатных моделей для скачивания", "Отличный вьюер"], en: ["Many free downloadable models", "Great viewer"] },
        cons: { ru: ["Лимит на загрузки в месяц"], en: ["Monthly upload limits"] },
        keywords: ["3d", "модели", "cg", "ассеты"],
        isHot: false,
        isNew: false
    },

    // --- ИГРЫ И ЖЕЛЕЗО (GAMING & PC) ---
    {
        id: "liquipedia",
        name: "Liquipedia",
        url: "https://liquipedia.net/",
        price: "free",
        category: { ru: "Игры", en: "Gaming" },
        desc: { ru: "Википедия киберспорта.", en: "The esports wiki." },
        fullDesc: { ru: "Самая полная база данных по турнирам, игрокам и патчам в Dota 2, Counter-Strike 2 и других киберспортивных дисциплинах.", en: "Most comprehensive database for tournaments, players, and patches in Dota 2, CS2, etc." },
        pros: { ru: ["Мгновенные обновления", "Сетка турниров онлайн"], en: ["Instant updates", "Live brackets"] },
        cons: { ru: ["Интерфейс на английском"], en: ["English interface mainly"] },
        keywords: ["dota2", "cs2", "киберспорт", "турниры"],
        isHot: false,
        isNew: false
    },
    {
        id: "steamdb",
        name: "SteamDB",
        url: "https://steamdb.info/",
        price: "free",
        category: { ru: "Игры", en: "Gaming" },
        desc: { ru: "База данных и статистика Steam.", en: "Steam database and stats." },
        fullDesc: { ru: "Показывает реальный онлайн в играх, историю изменения цен, скрытые скидки и точную стоимость вашего аккаунта.", en: "Shows real player counts, price history, hidden sales, and account value." },
        pros: { ru: ["История самых низких цен", "Никакой рекламы"], en: ["All-time low price history", "No ads"] },
        cons: { ru: ["Нужно привязать Steam для точных данных"], en: ["Requires Steam login for personal stats"] },
        keywords: ["steam", "скидки", "игры", "статистика"],
        isHot: false,
        isNew: false
    },
    {
        id: "pcpartpicker",
        name: "PCPartPicker",
        url: "https://pcpartpicker.com/",
        price: "free",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Сборка ПК и проверка совместимости.", en: "PC builder & compatibility checker." },
        fullDesc: { ru: "Помогает собрать мощный игровой ПК. Система сама проверит, влезет ли кулер в корпус и хватит ли блока питания для вашей видеокарты.", en: "Helps build a PC. Automatically checks compatibility of parts (CPU, GPU, PSU, etc)." },
        pros: { ru: ["Точная проверка совместимости", "Сборки пользователей"], en: ["Accurate compatibility check", "User builds"] },
        cons: { ru: ["Цены ориентированы на западные магазины"], en: ["Prices based on western stores"] },
        keywords: ["пк", "железо", "сборка", "процессор"],
        isHot: false,
        isNew: false
    },

    // --- ПУТЕШЕСТВИЯ (TRAVEL) ---
    {
        id: "trip-com",
        name: "Trip.com",
        url: "https://www.trip.com/",
        price: "free",
        category: { ru: "Путешествия", en: "Travel" },
        desc: { ru: "Бронирование билетов и отелей (Топ для Азии).", en: "Flight & hotel booking (Great for Asia)." },
        fullDesc: { ru: "Одно из лучших приложений для планирования поездок, особенно незаменимо при путешествиях в страны Азии. Работает с местными авиалиниями и поездами.", en: "One of the best apps for travel planning, especially indispensable for trips to Asia." },
        pros: { ru: ["Покупка билетов на поезда", "Отличная поддержка"], en: ["Buy train tickets", "Great support"] },
        cons: { ru: ["Цены иногда меняются на этапе оплаты"], en: ["Prices can change at checkout"] },
        keywords: ["билеты", "азия", "путешествие", "отели"],
        isHot: false,
        isNew: false
    },
    {
        id: "rome2rio",
        name: "Rome2Rio",
        url: "https://www.rome2rio.com/",
        price: "free",
        category: { ru: "Путешествия", en: "Travel" },
        desc: { ru: "Как добраться куда угодно.", en: "How to get anywhere." },
        fullDesc: { ru: "Показывает абсолютно все способы добраться из точки А в точку Б: самолеты, поезда, автобусы, паромы и даже такси с примерными ценами.", en: "Shows all ways to get from point A to B: flights, trains, buses, ferries with estimated prices." },
        pros: { ru: ["Охватывает весь мир", "Очень наглядно"], en: ["Covers the whole world", "Highly visual"] },
        cons: { ru: ["Расписание автобусов бывает неточным"], en: ["Bus schedules can be inaccurate"] },
        keywords: ["маршрут", "поездка", "карта", "транспорт"],
        isHot: false,
        isNew: false
    },
    // --- НОВОЕ МЕГА-ПОПОЛНЕНИЕ (20 САЙТОВ) ---
    {
        id: "claude-ai",
        name: "Claude",
        url: "https://claude.ai/",
        price: "freemium",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "Главный конкурент ChatGPT от Anthropic.", en: "Top ChatGPT competitor by Anthropic." },
        fullDesc: { ru: "Умнейшая нейросеть с огромным контекстным окном. Пишет гениальный код, великолепно анализирует длинные документы и звучит более естественно (как человек), чем аналоги.", en: "Brilliant AI with a huge context window. Writes incredible code, analyzes long documents, and sounds more human than competitors." },
        pros: { ru: ["Лучший стиль написания текста", "Пишет чистый код"], en: ["Best writing style", "Writes clean code"] },
        cons: { ru: ["Меньше функций, чем у GPT-4"], en: ["Fewer features than GPT-4"] },
        keywords: ["claude", "ai", "текст", "код", "нейросеть"],
        isHot: false,
        isNew: false
    },
    {
        id: "elevenlabs",
        name: "ElevenLabs",
        url: "https://elevenlabs.io/",
        price: "freemium",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "Самая реалистичная озвучка текста.", en: "Most realistic text-to-speech AI." },
        fullDesc: { ru: "Генерирует голос, который невозможно отличить от настоящего. Идеально для озвучки роликов, презентаций или клонирования собственного голоса.", en: "Generates voices indistinguishable from humans. Perfect for voiceovers, presentations, or voice cloning." },
        pros: { ru: ["Абсолютный реализм", "Клонирование голоса"], en: ["Absolute realism", "Voice cloning"] },
        cons: { ru: ["Бесплатных символов мало"], en: ["Free characters are limited"] },
        keywords: ["голос", "аудио", "озвучка", "tts", "ai"],
        isHot: false,
        isNew: false
    },
    {
        id: "runwayml",
        name: "Runway",
        url: "https://runwayml.com/",
        price: "freemium",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "Генерация и редактирование видео через ИИ.", en: "AI video generation and editing." },
        fullDesc: { ru: "Платформа Gen-2 позволяет создавать полноценные видеоролики по текстовому описанию или анимировать статичные картинки.", en: "Gen-2 platform allows generating full video clips from text prompts or animating static images." },
        pros: { ru: ["Магия анимации картинок", "Мощные инструменты монтажа"], en: ["Image animation magic", "Powerful editing tools"] },
        cons: { ru: ["Видео генерируются короткими (по 4 сек)"], en: ["Generates short videos (4s)"] },
        keywords: ["видео", "монтаж", "анимация", "генерация"],
        isHot: false,
        isNew: false
    },
    {
        id: "canva",
        name: "Canva",
        url: "https://www.canva.com/",
        price: "freemium",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "Универсальный онлайн-редактор дизайна.", en: "Universal online design editor." },
        fullDesc: { ru: "Создание превью для YouTube, презентаций, постов и визиток за 5 минут. Миллионы шаблонов и встроенные ИИ-инструменты.", en: "Create YouTube thumbnails, presentations, and posts in 5 minutes. Millions of templates and built-in AI." },
        pros: { ru: ["Справится даже ребенок", "Огромная библиотека элементов"], en: ["Extremely easy to use", "Huge element library"] },
        cons: { ru: ["Многие крутые шаблоны в Pro-версии"], en: ["Many cool templates are Pro-only"] },
        keywords: ["дизайн", "шаблоны", "презентации", "графика"],
        isHot: false,
        isNew: false
    },
    {
        id: "svgomg",
        name: "SVGOMG",
        url: "https://jakearchibald.github.io/svgomg/",
        price: "free",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "Оптимизатор SVG файлов для веба.", en: "SVG file optimizer for web." },
        fullDesc: { ru: "Мастхэв для фронтенд-разработчиков и веб-дизайнеров. Очищает SVG-код от мусора и уменьшает размер файла в несколько раз без потери качества.", en: "Must-have for frontend devs. Cleans SVG code from trash and reduces file size significantly without quality loss." },
        pros: { ru: ["Полностью бесплатно", "Работает в браузере"], en: ["Completely free", "Works in browser"] },
        cons: { ru: ["Интерфейс на любителя"], en: ["UI is an acquired taste"] },
        keywords: ["svg", "вектор", "оптимизация", "код"],
        isHot: false,
        isNew: false
    },
    {
        id: "codepen",
        name: "CodePen",
        url: "https://codepen.io/",
        price: "freemium",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Песочница для фронтенд-кода.", en: "Frontend code sandbox." },
        fullDesc: { ru: "Лучшее место для написания, тестирования и сохранения сниппетов HTML, CSS и JS. Миллионы готовых анимаций и кусков кода от комьюнити.", en: "Best place to write, test, and save HTML, CSS, and JS snippets. Millions of community creations." },
        pros: { ru: ["Мгновенный рендер кода", "Отличный источник вдохновения"], en: ["Instant code render", "Great inspiration source"] },
        cons: { ru: ["Приватные проекты платные"], en: ["Private pens are paid"] },
        keywords: ["html", "css", "js", "код", "песочница"],
        isHot: false,
        isNew: false
    },
    {
        id: "css-gradient",
        name: "CSS Gradient",
        url: "https://cssgradient.io/",
        price: "free",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Генератор красивых CSS-градиентов.", en: "Beautiful CSS gradient generator." },
        fullDesc: { ru: "Удобный визуальный конструктор для создания сложных фонов. Настроил цвета — скопировал одну строчку CSS-кода в свой проект.", en: "Visual builder for complex backgrounds. Tweak colors and copy one line of CSS to your project." },
        pros: { ru: ["Очень просто", "Есть готовые популярные пресеты"], en: ["Very simple", "Has popular ready presets"] },
        cons: { ru: ["Ограниченный функционал"], en: ["Limited to just gradients"] },
        keywords: ["css", "градиент", "дизайн", "фон", "верстка"],
        isHot: false,
        isNew: false
    },
    {
        id: "regex101",
        name: "Regex101",
        url: "https://regex101.com/",
        price: "free",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Тестировщик регулярных выражений.", en: "Regular expressions tester." },
        fullDesc: { ru: "Спасательный круг для программистов. Помогает писать, тестировать и понимать сложные регулярные выражения с подсветкой синтаксиса.", en: "Lifesaver for programmers. Helps write, test, and understand complex regular expressions with syntax highlighting." },
        pros: { ru: ["Объясняет каждый символ регулярки", "Поддержка разных языков (JS, Python)"], en: ["Explains every regex character", "Supports JS, Python, etc."] },
        cons: { ru: ["Сложно для новичков в программировании"], en: ["Hard for absolute beginners"] },
        keywords: ["regex", "код", "регулярки", "разработка"],
        isHot: false,
        isNew: false
    },
    {
        id: "obsidian",
        name: "Obsidian",
        url: "https://obsidian.md/",
        price: "free",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Второй мозг для заметок.", en: "Second brain for notes." },
        fullDesc: { ru: "Супермощный текстовый редактор на базе Markdown. Создает графы связей между вашими мыслями, конспектами и идеями. Все файлы хранятся локально у вас.", en: "Super powerful Markdown note-taking app. Creates graphs linking your thoughts. All files stored locally." },
        pros: { ru: ["Полный контроль над данными", "Сотни плагинов"], en: ["Full data control", "Hundreds of plugins"] },
        cons: { ru: ["Синхронизация между устройствами платная"], en: ["Cloud sync is paid"] },
        keywords: ["заметки", "мозг", "markdown", "база знаний"],
        isHot: false,
        isNew: false
    },
    {
        id: "12ft-ladder",
        name: "12ft Ladder",
        url: "https://12ft.io/",
        price: "free",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Обход платных подписок на статьи.", en: "Bypass paywalls on articles." },
        fullDesc: { ru: "Сервис убирает всплывающие окна 'оплатите, чтобы дочитать статью', притворяясь поисковым роботом Google. Отлично работает на новостных сайтах.", en: "Removes 'pay to read' popups by pretending to be a Google crawler. Works great on news sites." },
        pros: { ru: ["Легко использовать", "Читает скрытый кэш"], en: ["Easy to use", "Reads hidden cache"] },
        cons: { ru: ["Не работает на некоторых крупных медиа (NYT)"], en: ["Doesn't work on some big media (NYT)"] },
        keywords: ["статьи", "чтение", "обход", "paywall"],
        isHot: false,
        isNew: false
    },
    {
        id: "bitwarden",
        name: "Bitwarden",
        url: "https://bitwarden.com/",
        price: "freemium",
        category: { ru: "Приватность", en: "Privacy" },
        desc: { ru: "Лучший бесплатный менеджер паролей.", en: "Best free password manager." },
        fullDesc: { ru: "Надежное хранилище паролей с открытым исходным кодом. Генерирует сложные пароли и автоматически подставляет их на сайтах и в приложениях.", en: "Reliable open-source password vault. Generates strong passwords and autofills them on sites." },
        pros: { ru: ["Бесплатная синхронизация на все устройства", "Открытый код"], en: ["Free sync across all devices", "Open source"] },
        cons: { ru: ["Интерфейс выглядит немного устаревшим"], en: ["UI looks a bit dated"] },
        keywords: ["пароли", "безопасность", "защита", "хранилище"],
        isHot: false,
        isNew: false
    },
    {
        id: "gramota-ru",
        name: "Грамота.ру",
        url: "https://gramota.ru/",
        price: "free",
        category: { ru: "Обучение", en: "Education" },
        desc: { ru: "Справочник по русскому языку.", en: "Russian language reference." },
        fullDesc: { ru: "Главный портал по русскому языку. Правила пунктуации, проверка слов по словарям и подробные разборы сложных правил (например, суффиксы -н- и -нн-).", en: "Main portal for the Russian language. Punctuation rules, dictionary checks, and detailed grammar explanations." },
        pros: { ru: ["Официальные словари", "Бесплатная справка от филологов"], en: ["Official dictionaries", "Free help from philologists"] },
        cons: { ru: ["Много устаревших статей на форуме"], en: ["Many outdated forum posts"] },
        keywords: ["русский", "правила", "словарь", "грамматика", "школа"],
        isHot: false,
        isNew: false
    },
    {
        id: "mathway",
        name: "Mathway",
        url: "https://www.mathway.com/",
        price: "freemium",
        category: { ru: "Обучение", en: "Education" },
        desc: { ru: "Мощный решатель математических задач.", en: "Powerful math problem solver." },
        fullDesc: { ru: "Справляется с любой школьной программой: от алгебры за 10 класс до сложной тригонометрии и статистики. Можно просто сфотографировать пример.", en: "Handles any school curriculum: from algebra to complex trigonometry. You can just snap a picture of the problem." },
        pros: { ru: ["Решает по фото", "Огромный охват тем"], en: ["Solves from photo", "Huge topic coverage"] },
        cons: { ru: ["Пошаговое решение требует подписку"], en: ["Step-by-step requires sub"] },
        keywords: ["математика", "учеба", "алгебра", "калькулятор", "решебник"],
        isHot: false,
        isNew: false
    },
    {
        id: "chemspider",
        name: "ChemSpider",
        url: "https://www.chemspider.com/",
        price: "free",
        category: { ru: "Обучение", en: "Education" },
        desc: { ru: "База данных химических структур.", en: "Chemical structure database." },
        fullDesc: { ru: "Огромная поисковая система по химии. Вводите название вещества (например, альдегиды) и получаете 2D/3D структуру, свойства и формулы.", en: "Huge chemistry search engine. Enter a substance name and get 2D/3D structures, properties, and formulas." },
        pros: { ru: ["Миллионы молекул", "Точнейшие данные"], en: ["Millions of molecules", "Highly accurate data"] },
        cons: { ru: ["Исключительно для учебы/науки"], en: ["Strictly for education/science"] },
        keywords: ["химия", "молекулы", "формулы", "наука"],
        isHot: false,
        isNew: false
    },
    {
        id: "prosettings",
        name: "ProSettings",
        url: "https://prosettings.net/",
        price: "free",
        category: { ru: "Игры", en: "Gaming" },
        desc: { ru: "Настройки и девайсы киберспортсменов.", en: "Esports pro settings & gear." },
        fullDesc: { ru: "База данных настроек про-игроков. Идеально для подбора прицела в CS2, DPI мышки или поиска идеального разрешения (включая растянутое 4:3).", en: "Database of pro player configs. Perfect for finding CS2 crosshairs, mouse DPI, or the perfect stretched 4:3 resolution." },
        pros: { ru: ["Готовые конфиги для скачивания", "Аналитика девайсов"], en: ["Ready to download configs", "Gear analytics"] },
        cons: { ru: ["Не все игроки обновляют данные часто"], en: ["Not all players update frequently"] },
        keywords: ["cs2", "dota2", "киберспорт", "настройки", "прицел", "конфиг"],
        isHot: false,
        isNew: false
    },
    {
        id: "leetify",
        name: "Leetify",
        url: "https://leetify.com/",
        price: "freemium",
        category: { ru: "Игры", en: "Gaming" },
        desc: { ru: "Глубокая аналитика матчей CS2.", en: "Deep CS2 match analytics." },
        fullDesc: { ru: "Автоматически анализирует демки твоих матчей в Counter-Strike 2. Показывает рейтинг аима, позиционирования, полезности раскидок и сравнивает с глобалами.", en: "Automatically analyzes your CS2 demos. Shows aim rating, positioning, utility damage, and compares you to pros." },
        pros: { ru: ["Объективная оценка скилла", "Анализ ошибок"], en: ["Objective skill rating", "Mistake analysis"] },
        cons: { ru: ["Много данных, нужно время чтобы разобраться"], en: ["Lots of data, takes time to understand"] },
        keywords: ["cs2", "статистика", "аим", "киберспорт", "анализ"],
        isHot: false,
        isNew: false
    },
    {
        id: "gg-deals",
        name: "GG.deals",
        url: "https://gg.deals/",
        price: "free",
        category: { ru: "Игры", en: "Gaming" },
        desc: { ru: "Поиск самых дешевых ключей на игры.", en: "Find cheapest game keys." },
        fullDesc: { ru: "Сравнивает цены на игры в официальных магазинах (Steam, Epic) и на сайтах по продаже ключей. Синхронизируется со списком желаемого.", en: "Compares game prices across official stores and key resellers. Syncs with your wishlist." },
        pros: { ru: ["Показывает исторический минимум цены", "Уведомления о скидках"], en: ["Shows historical low prices", "Sale alerts"] },
        cons: { ru: ["Некоторые магазины ключей серые"], en: ["Some key shops are grey market"] },
        keywords: ["игры", "скидки", "steam", "ключи", "дешево"],
        isHot: false,
        isNew: false
    },
    {
        id: "maps-me",
        name: "MAPS.ME",
        url: "https://maps.me/",
        price: "free",
        category: { ru: "Путешествия", en: "Travel" },
        desc: { ru: "Детализированные оффлайн карты.", en: "Detailed offline maps." },
        fullDesc: { ru: "Скачиваешь карту страны дома — и она работает за границей без интернета. Незаменимая вещь в поездках, строит маршруты для пешеходов и авто.", en: "Download a country map at home and use it abroad without internet. Builds routes for walking and driving." },
        pros: { ru: ["Работает без сим-карты/eSIM", "Знает все тропинки"], en: ["Works without SIM/eSIM", "Knows every tiny path"] },
        cons: { ru: ["Карты занимают много памяти телефона"], en: ["Maps take up a lot of storage"] },
        keywords: ["карты", "gps", "оффлайн", "путешествия", "маршрут"],
        isHot: false,
        isNew: false
    },
    {
        id: "skyscanner",
        name: "Skyscanner",
        url: "https://www.skyscanner.net/",
        price: "free",
        category: { ru: "Путешествия", en: "Travel" },
        desc: { ru: "Ультимативный поиск авиабилетов.", en: "Ultimate flight search." },
        fullDesc: { ru: "Сравнивает цены у сотен авиакомпаний. Фишка 'Везде' позволяет найти самые дешевые билеты куда угодно из вашего города.", en: "Compares prices across hundreds of airlines. The 'Everywhere' feature finds cheapest flights to anywhere from your city." },
        pros: { ru: ["Удобный календарь цен", "Функция поиска 'Везде'"], en: ["Great price calendar", "Search 'Everywhere' feature"] },
        cons: { ru: ["Часто перекидывает на сторонние агентства"], en: ["Often redirects to 3rd party agencies"] },
        keywords: ["билеты", "авиа", "перелет", "отпуск"],
        isHot: false,
        isNew: false
    },
    // --- ТОП-25 НОВЫХ КРУТЫХ ИНСТРУМЕНТОВ ---
    {
        id: "excalidraw",
        name: "Excalidraw",
        url: "https://excalidraw.com/",
        price: "free",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "Виртуальная доска со стилем рисунка от руки.", en: "Virtual whiteboard with a hand-drawn sketch style." },
        fullDesc: { ru: "Идеальный инструмент для быстрого наброска схем, архитектуры приложений или проведения брейнштормов. Картинка выглядит так, будто её нарисовали маркером на доске.", en: "Excellent tool for sketching diagrams, software architecture, or wireframes with a distinct hand-drawn feel." },
        pros: { ru: ["Полностью бесплатно", "Удобная совместная работа", "Поддерживает шифрование"], en: ["100% free", "Great collaboration", "End-to-end encryption"] },
        cons: { ru: ["Нет сложных инструментов для точного черчения"], en: ["Lacks precision tools for advanced blueprints"] },
        keywords: ["excalidraw", "дизайн", "доска", "схемы", "рисунок", "whiteboard"],
        isHot: false,
        isNew: false
    },
    {
        id: "ray-so",
        name: "Ray.so",
        url: "https://ray.so/",
        price: "free",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Создание красивых скриншотов кода.", en: "Create beautiful images of your code." },
        fullDesc: { ru: "Позволяет превратить унылый кусок исходного кода в стильное изображение с градиентным фоном, авто-подсветкой синтаксиса и точной настройкой темы. Идеально для блогов и соцсетей.", en: "Turns your raw code snippets into stunning artwork with custom background gradients, shadows, and flawless syntax highlighting." },
        pros: { ru: ["Быстрая работа без регистрации", "Много современных тем"], en: ["Very fast, no login required", "Tons of modern themes"] },
        cons: { ru: ["Нельзя кастомизировать шрифт в бесплатной версии"], en: ["Cannot customize fonts in the base version"] },
        keywords: ["code", "screenshot", "ray", "код", "красиво", "скриншот"],
        isHot: false,
        isNew: false
    },
    {
        id: "json-crack",
        name: "JSON Crack",
        url: "https://jsoncrack.com/",
        price: "freemium",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Визуализация JSON в виде интерактивных графов.", en: "Visualize JSON data into interactive graphs." },
        fullDesc: { ru: "Инструмент мгновенно трансформирует сложные и вложенные структуры JSON-файлов в наглядные древовидные диаграммы, которые можно скачивать и анализировать.", en: "Instantly transforms complex, nested JSON structures into easily readable, interactive tree diagrams." },
        pros: { ru: ["Наглядный поиск путей к свойствам", "Упрощает дебаг крупных API-ответов"], en: ["Visual property path tracking", "Simplifies debugging massive API responses"] },
        cons: { ru: ["Тяжелые файлы могут подтормаживать в браузере"], en: ["Massive datasets can cause slight browser lag"] },
        keywords: ["json", "crack", "визуализация", "дерево", "код", "api"],
        isHot: false,
        isNew: false
    },
    {
        id: "deepl",
        name: "DeepL",
        url: "https://www.deepl.com/",
        price: "freemium",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Самый точный ИИ-переводчик в мире.", en: "The most accurate AI translator globally." },
        fullDesc: { ru: "Переводчик на базе продвинутых нейронных сетей, который улавливает тончайшие контекстные нюансы текста и переводит гораздо естественнее, чем классические аналоги.", en: "An AI-powered translation service that captures deep contextual nuances, delivering highly natural-sounding translations." },
        pros: { ru: ["Понимает технический и сленговый контекст", "Встроенный глоссарий"], en: ["Excellent with technical and slang context", "Built-in glossary"] },
        cons: { ru: ["Лимит на количество символов в бесплатном режиме"], en: ["Character limits on the free tier"] },
        keywords: ["переводчик", "deepl", "текст", "язык", "словарь"],
        isHot: false,
        isNew: false
    },
    {
        id: "phind",
        name: "Phind",
        url: "https://www.phind.com/",
        price: "freemium",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "Умный поисковик для разработчиков.", en: "Intelligent search engine for developers." },
        fullDesc: { ru: "Специализированная нейросеть-поисковик. Вместо кучи ссылок она сразу выдает структурированное объяснение, документацию и готовый рабочий код под твою задачу.", en: "An AI search engine built specifically for developers. It aggregates web data to write structured solutions with working code." },
        pros: { ru: ["Ищет по свежей документации", "Генерирует чистый код"], en: ["Searches live documentation", "Generates production-ready code"] },
        cons: { ru: ["Иногда может проигнорировать редкие фреймворки"], en: ["Can occasionally miss niche or legacy frameworks"] },
        keywords: ["phind", "ai", "поиск", "код", "разработка", "нейросеть"],
        isHot: false,
        isNew: false
    },
    {
        id: "framer",
        name: "Framer",
        url: "https://www.framer.com/",
        price: "freemium",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Конструктор сайтов с механиками Figma.", en: "Website builder that works like Figma." },
        fullDesc: { ru: "Профессиональная платформа, которая позволяет собирать сайты прямо на бесконечной канве, настраивая невероятную сложную анимацию интерфейсов без кода.", en: "Design and publish high-performance interactive websites on a freeform canvas without managing infrastructure or code." },
        pros: { ru: ["Прямой импорт слоев из Figma", "Потрясающая плавная анимация"], en: ["Direct layer import from Figma", "Stunning scroll and click animations"] },
        cons: { ru: ["Дорогой хостинг на платных тарифах"], en: ["Paid hosting tiers can be quite expensive"] },
        keywords: ["framer", "дизайн", "сайт", "nocode", "анимация", "конструктор"],
        isHot: false,
        isNew: false
    },
    {
        id: "carrd",
        name: "Carrd",
        url: "https://carrd.co/",
        price: "freemium",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Конструктор простых одностраничных сайтов.", en: "Simple and responsive one-page site builder." },
        fullDesc: { ru: "Идеальный инструмент для создания адаптивных визиток, портфолио, форм сбора заявок или минималистичных посадочных страниц за 15 минут.", en: "A streamlined platform designed exclusively for building fully responsive single-page websites, portfolios, and forms." },
        pros: { ru: ["Невероятно легкий и быстрый", "Очень дешевая Pro-версия"], en: ["Incredibly fast and lightweight", "Very affordable premium plan"] },
        cons: { ru: ["Ограничен только одной страницей в рамках проекта"], en: ["Strictly limited to single-page layouts"] },
        keywords: ["carrd", "лендинг", "сайт", "одностраничник", "портфолио"],
        isHot: false,
        isNew: false
    },
    {
        id: "supabase",
        name: "Supabase",
        url: "https://supabase.com/",
        price: "freemium",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Открытая альтернатива Firebase на PostgreSQL.", en: "The open source Firebase alternative built on PostgreSQL." },
        fullDesc: { ru: "Предоставляет готовую полноценную базу данных PostgreSQL, аутентификацию пользователей, real-time подписки и хранилище файлов из коробки.", en: "An open-source backend-as-a-service providing a full PostgreSQL database, auth, instant APIs, and storage." },
        pros: { ru: ["Настоящий мощный SQL", "Автоматическая генерация REST API"], en: ["True powerful SQL environment", "Auto-generated REST APIs"] },
        cons: { ru: ["Требует понимания базовых концепций реляционных баз"], en: ["Requires basic knowledge of relational DB concepts"] },
        keywords: ["supabase", "база", "бэкенд", "database", "firebase", "sql"],
        isHot: false,
        isNew: false
    },
    {
        id: "svg-repo",
        name: "SVG Repo",
        url: "https://www.svgrepo.com/",
        price: "free",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "Огромная библиотека бесплатных SVG-иконок.", en: "Massive library of free SVG vectors and icons." },
        fullDesc: { ru: "Более 500 000 векторных элементов и векторов, доступных для коммерческого использования. Позволяет скачивать или копировать чистый SVG-код.", en: "An inventory of over 500,000 vector graphics optimized for easy search, direct download, or copying vector code." },
        pros: { ru: ["Полностью бесплатно", "Удобное разделение по пакам и стилям"], en: ["Completely free", "Nicely categorized by vector packs and styles"] },
        cons: { ru: ["Поиск иногда выдает слишком много похожих иконок"], en: ["Search results can sometimes yield overly redundant variations"] },
        keywords: ["svg", "иконки", "вектор", "repo", "дизайн", "icons"],
        isHot: false,
        isNew: false
    },
    {
        id: "iconify",
        name: "Iconify",
        url: "https://iconify.design/",
        price: "free",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "Единый фреймворк для всех существующих паков иконок.", en: "Unified icon framework for countless icon sets." },
        fullDesc: { ru: "Объединяет в одном месте иконки из Material Design, FontAwesome, Lucide, Remix Icons и сотен других наборов. Можно подключать как компоненты в код.", en: "A massive open-source library consolidating icons from standard icon sheets into one searchable component interface." },
        pros: { ru: ["Доступ вообще ко всем популярным наборам", "Легкая интеграция в React/Vue/Flutter"], en: ["Access to practically every popular pack", "Easy integration into React/Vue/Flutter"] },
        cons: { ru: ["Аскетичный поисковый веб-интерфейс"], en: ["The web search interface is highly barebones"] },
        keywords: ["iconify", "иконки", "разработка", "дизайн", "pack", "lucide"],
        isHot: false,
        isNew: false
    },
    {
        id: "diffchecker",
        name: "Diffchecker",
        url: "https://www.diffchecker.com/",
        price: "freemium",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Онлайн-инструмент сравнения файлов.", en: "Compare text, images, and files to find differences." },
        fullDesc: { ru: "Помогает мгновенно найти различия между двумя текстами, фрагментами кода, изображениями, таблицами или PDF-документами, подсвечивая изменения.", en: "A comparison platform that tracks and highlights textual edits, code modifications, images, and PDFs side by side." },
        pros: { ru: ["Сравнивает даже бинарные файлы и картинки", "Удобная подсветка"], en: ["Compares images and binary files", "Clear differential highlighting"] },
        cons: { ru: ["Наличие навязчивой рекламы в бесплатной версии"], en: ["Intrusive ad layouts on the free version"] },
        keywords: ["diff", "сравнение", "текст", "код", "checker", "файлы"],
        isHot: false,
        isNew: false
    },
    {
        id: "cyberchef",
        name: "CyberChef",
        url: "https://gchq.github.io/CyberChef/",
        price: "free",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Кибер-швейцарский нож для любых операций с данными.", en: "The cyber Swiss Army Knife for data operations." },
        fullDesc: { ru: "Проект от спецслужб Великобритании для шифрования, дешифрования, конвертации форматов, парсинга строк, кодирования в Base64, Hex и работы с хешами.", en: "A complex web app created for heavy formatting, encoding, parsing, hashing, and structural operations with data." },
        pros: { ru: ["Работает полностью локально на клиенте", "Тысячи комбинаций функций"], en: ["Runs fully client-side and offline", "Thousands of data processing nodes"] },
        cons: { ru: ["Интерфейс выглядит пугающе сложно для новичков"], en: ["The highly technical layout can look intimidating for beginners"] },
        keywords: ["cyberchef", "декодер", "инструменты", "хеш", "крипто", "base64"],
        isHot: false,
        isNew: false
    },
    {
        id: "scribe",
        name: "Scribe",
        url: "https://scribehow.com/",
        price: "freemium",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Автоматическое создание пошаговых инструкций.", en: "Turn any process into a step-by-step guide instantly." },
        fullDesc: { ru: "Ты просто выполняешь задачу на экране, а расширение автоматически записывает твои клики, делает скриншоты и оформляет красивый пошаговый гайд.", en: "Captures your browser actions and instantly auto-generates flawless, screenshot-heavy visual guides and SOPs." },
        pros: { ru: ["Колоссальная экономия времени на мануалах", "Чистый дизайн макетов"], en: ["Massive time saver for tutorials", "Beautifully polished documentation design"] },
        cons: { ru: ["Размытие конфиденциальных данных на скриншотах — фича Pro"], en: ["Smart blurring of sensitive info requires a Pro subscription"] },
        keywords: ["scribe", "гайд", "инструкция", "скриншоты", "tools", "документация"],
        isHot: false,
        isNew: false
    },
    {
        id: "loom",
        name: "Loom",
        url: "https://www.loom.com/",
        price: "freemium",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Быстрая запись экрана и видеосообщений.", en: "Video messaging and screen recording tool." },
        fullDesc: { ru: "Позволяет записать экран и веб-камеру одновременно. Ссылка на видео генерируется мгновенно прямо в процессе записи — не надо ничего выгружать.", en: "Simultaneously records your desktop screen and face camera, spinning up an instantly shareable web link as soon as you hit stop." },
        pros: { ru: ["Идеально для видео-ответов коллегам", "Автоматические субтитры"], en: ["Flawless async video communications", "Automated video transcripts"] },
        cons: { ru: ["Лимит на бесплатную запись составляет всего 5 минут"], en: ["Free video records are restricted to 5 minutes max"] },
        keywords: ["loom", "видео", "запись", "экран", "шеринг", "камера"],
        isHot: false,
        isNew: false
    },
    {
        id: "linear",
        name: "Linear",
        url: "https://linear.app/",
        price: "freemium",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Лучший и самый быстрый таск-трекер для IT.", en: "The issue tracker you'll enjoy using." },
        fullDesc: { ru: "Сверхбыстрый и эргономичный менеджер задач, созданный специально для софтверных команд. Работает без перезагрузок и управляется с клавиатуры.", en: "An incredibly fast, keyboard-shortcut-driven project management tracker optimized for modern agile software development." },
        pros: { ru: ["Молниеносный интерфейс", "Шикарные горячие клавиши"], en: ["Insanely responsive interface", "Brilliant keyboard shortcut flow"] },
        cons: { ru: ["Специфичен для разработки, не подойдет классическому бизнесу"], en: ["Very specific to engineering, poor fit for traditional trade fields"] },
        keywords: ["linear", "задачи", "таск-трекер", "pm", "agile", "управление"],
        isHot: false,
        isNew: false
    },
    {
        id: "tldraw",
        name: "tldraw",
        url: "https://www.tldraw.com/",
        price: "free",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "Ультра-минималистичная и быстрая онлайн-доска.", en: "A tiny, lightning-fast digital canvas." },
        fullDesc: { ru: "Легковесный холст для рисования схем и заметок. Моментально открывается, не перегружен лишними меню и полностью бесплатен.", en: "A lightweight collaborative drawing canvas that focuses on immediate performance and elegant vector stroke rendering." },
        pros: { ru: ["Запускается за доли секунды", "Открытый исходный код"], en: ["Loads up in fractions of a second", "Open-source under active development"] },
        cons: { ru: ["Меньше встроенных шаблонов, чем в Miro или Figma"], en: ["Fewer prebuilt template schemas than Miro or Figma"] },
        keywords: ["tldraw", "доска", "схемы", "дизайн", "whiteboard", "канва"],
        isHot: false,
        isNew: false
    },
    {
        id: "hugging-face",
        name: "Hugging Face",
        url: "https://huggingface.co/",
        price: "free",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "Главная мировая платформа ИИ с открытым кодом.", en: "The hub for open-source AI and ML models." },
        fullDesc: { ru: "Центральное комьюнити, где разработчики делятся предобученными ИИ-моделями, датасетами и веб-приложениями (Spaces) для тестирования нейросетей.", en: "The prominent collective ecosystem hosting thousands of open-weight ML layers, translation nodes, and interactive AI web blocks." },
        pros: { ru: ["Доступ к тысячам бесплатных ИИ моделей", "Можно бесплатно запустить веб-демо"], en: ["Access to thousands of open models", "Free hosted demo sandboxes (Spaces)"] },
        cons: { ru: ["Очень сложная техническая платформа для обывателя"], en: ["Highly advanced code architecture, overwhelming for non-developers"] },
        keywords: ["ai", "models", "huggingface", "нейросети", "датасеты", "hub"],
        isHot: false,
        isNew: false
    },
    {
        id: "vercel",
        name: "Vercel",
        url: "https://vercel.com/",
        price: "freemium",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Хостинг и деплой фронтенда в один клик.", en: "Platform for frontend developers to deploy instantly." },
        fullDesc: { ru: "Идеальное решение для размещения веб-сайтов (особенно на Next.js, React или простом HTML). Интегрируется с GitHub и деплоит сайт при каждом пуше.", en: "Provides serverless hosting architecture and global edge CDN routing optimized for responsive web apps." },
        pros: { ru: ["Автоматический SSL и превью-ссылки для веток", "Очень быстрый глобальный CDN"], en: ["Automatic SSL and custom branch previews", "Ultra-fast global edge infrastructure"] },
        cons: { ru: ["Строгие лимиты на пропускной трафик (bandwidth) на бесплатных аккаунтах"], en: ["Strict data bandwidth limitations on the hobby tier"] },
        keywords: ["vercel", "хостинг", "деплой", "nextjs", "разработка", "веб"],
        isHot: false,
        isNew: false
    },
    {
        id: "shadcn-ui",
        name: "shadcn/ui",
        url: "https://ui.shadcn.com/",
        price: "free",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Прекрасно спроектированные UI-компоненты.", en: "Beautifully designed components that you can copy and paste." },
        fullDesc: { ru: "Новый подход к веб-интерфейсам: это не библиотека из npm, а набор готового кода на Tailwind и Radix, который ты копируешь прямо к себе в проект и полностью контролируешь.", en: "A selection of accessible component modules styled with Tailwind CSS, built to be injected straight into your repository codebase." },
        pros: { ru: ["Абсолютная свобода кастомизации", "Код принадлежит тебе, никаких зависимостей"], en: ["100% style control layout", "No package lock-ins, code is completely yours"] },
        cons: { ru: ["Нужно настраивать архитектуру стилей и компонентов вручную в самом начале"], en: ["Requires structure scaffolding initialization at project birth"] },
        keywords: ["shadcn", "ui", "компоненты", "react", "tailwind", "верстка"],
        isHot: false,
        isNew: false
    },
    {
        id: "font-awesome",
        name: "Font Awesome",
        url: "https://fontawesome.com/",
        price: "freemium",
        category: { ru: "Дизайн", en: "Design" },
        desc: { ru: "Самый известный в вебе набор иконок.", en: "The web's most popular icon set and toolkit." },
        fullDesc: { ru: "Классический и проверенный временем пак шрифтовых и векторных иконок, используемый миллионами сайтов по всему миру.", en: "A comprehensive design asset package containing thousands of scalable vector asset layers and web fonts." },
        pros: { ru: ["Легко подключается одной строчкой кода через CDN", "Стабильная поддержка годами"], en: ["Incredibly straightforward script injection setup", "Extremely stable lifetime code reliability"] },
        cons: { ru: ["Многие новые и интересные стили доступны только в платной версии Pro"], en: ["A large chunk of modern line variations are paywalled under Pro"] },
        keywords: ["иконки", "шрифты", "font", "awesome", "дизайн", "вектор"],
        isHot: false,
        isNew: false
    },
    {
        id: "heptabase",
        name: "Heptabase",
        url: "https://heptabase.com/",
        price: "paid",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Визуальный менеджер знаний для сложных исследований.", en: "Visual note-taking tool for deep learning and research." },
        fullDesc: { ru: "Помогает разложить сложные концепции, идеи и заметки на бесконечных интерактивных интеллект-картах и досках. Идеально для структурирования информации.", en: "A powerful spatial data mapping canvas designed to manage core notes, PDF highlights, and timeline whiteboards." },
        pros: { ru: ["Уникальный визуальный контекст связей", "Прекрасная работа с PDF источниками"], en: ["Unrivaled visual card connectivity layout", "Exceptional handling of native PDF text extraction"] },
        cons: { ru: ["Полностью платная модель, нет бесплатной версии (только триал)"], en: ["Strictly paid subscription service, missing an open free layer"] },
        keywords: ["heptabase", "заметки", "карты", "визуализация", "brain", "база"],
        isHot: false,
        isNew: false
    },
    {
        id: "airtable",
        name: "Airtable",
        url: "https://airtable.com/",
        price: "freemium",
        category: { ru: "Инструменты", en: "Tools" },
        desc: { ru: "Гибрид Excel и мощной реляционной базы данных.", en: "Low-code platform for building collaborative apps." },
        fullDesc: { ru: "Выглядит как простая таблица, но умеет связывать строки между собой, хранить файлы, строить канбан-доски и запускать автоматизации процессов.", en: "Combines the simplicity of a spreadsheet view with the heavy analytical engine of a relational database structure." },
        pros: { ru: ["Максимальная гибкость отображения данных", "Удобные интеграции с веб-хуками"], en: ["Incredibly diverse data viewing pipelines", "Strong webhook and integration connectors"] },
        cons: { ru: ["Бесплатная версия сильно урезана по числу строк в таблице"], en: ["Free accounts have strict caps on database record counts"] },
        keywords: ["airtable", "таблицы", "база", "excel", "инструменты", "nocode"],
        isHot: false,
        isNew: false
    },
    {
        id: "replit",
        name: "Replit",
        url: "https://replit.com/",
        price: "freemium",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Полноценная среда разработки (IDE) в твоем браузере.", en: "Code, deploy, and ship software straight from the browser." },
        fullDesc: { ru: "Позволяет писать код, компилировать проекты, работать со встроенным ИИ-ассистентом и мгновенно деплоить приложения без установки локального софта.", en: "A fully collaborative cloud container environment supporting dozens of runtimes alongside native AI assistance." },
        pros: { ru: ["Работает даже со слабого ноутбука или планшета", "Встроенное ИИ-автодополнение"], en: ["Runs smoothly even on basic Chromebooks or tablets", "Built-in smart AI autocompletion features"] },
        cons: { ru: ["Все проекты на бесплатном тарифе видны всему интернету (публичные)"], en: ["Free tier sandboxes are strictly public to the open web"] },
        keywords: ["replit", "код", "ide", "песочница", "онлайн", "программирование"],
        isHot: false,
        isNew: false
    },
    {
        id: "postman",
        name: "Postman",
        url: "https://www.postman.com/",
        price: "freemium",
        category: { ru: "Разработка", en: "Dev" },
        desc: { ru: "Главная платформа для разработки и тестирования API.", en: "The absolute standard toolkit for API building and testing." },
        fullDesc: { ru: "Инструмент для отправки HTTP-запросов к бэкенду. Позволяет создавать коллекции тестов, автоматизировать проверки эндпоинтов и писать скрипты.", en: "An industry-defining workspace platform engineered to build, mock, test, document, and monitor custom web APIs." },
        pros: { ru: ["Идеально для проверки интеграций бэкенда", "Удобные переменные окружения"], en: ["Flawless engine for mocking backend flows", "Highly modular environment variables"] },
        cons: { ru: ["В последнее время десктопный клиент стал перегруженным и тяжелым"], en: ["The native system clients have become noticeably cluttered over time"] },
        keywords: ["api", "postman", "тестирование", "запросы", "разработка", "backend"],
        isHot: false,
        isNew: false
    },
    {
        id: "krea-ai",
        name: "Krea AI",
        url: "https://www.krea.ai/",
        price: "freemium",
        category: { ru: "Нейросети", en: "AI" },
        desc: { ru: "Генерация и улучшение изображений в реальном времени.", en: "Real-time AI generation and upscale engine." },
        fullDesc: { ru: "Нейросеть генерирует картинку на лету, пока ты водишь мышкой или делаешь грубый набросок кистью. Также содержит один из лучших апскейлеров.", en: "A powerful prompt canvas that processes neural images in real-time as you sketch vector blocks, paired with industrial-grade upscaling." },
        pros: { ru: ["Уникальный интерактивный холст рисования", "Потрясающая детализация лиц при апскейле"], en: ["Mind-blowing real-time responsive canvas pipeline", "Incredible texture recovery during image upgrades"] },
        cons: { ru: ["Бешеное потребление ресурсов, требует стабильный и быстрый интернет"], en: ["High data streaming bandwidth demand, mandates robust internet channels"] },
        keywords: ["krea", "ai", "генерация", "дизайн", "апскейл", "нейросеть"],
        isHot: false,
        isNew: false
    }
];
